Update Jenkinsfile

diff --git a/misc/Jenkinsfile b/misc/Jenkinsfile
--- a/misc/Jenkinsfile
+++ b/misc/Jenkinsfile
@@ -36,9 +36,16 @@ pipeline {
                             echo "Logging into Docker Hub..."
                             echo "\$DOCKER_PASS" | docker login -u "\$DOCKER_USER" --password-stdin
 
+                            echo "Checking if Buildx is available..."
+                            if ! docker buildx version > /dev/null 2>&1; then
+                                echo "Buildx is missing, installing..."
+                                mkdir -p ~/.docker/cli-plugins
+                                curl -sL https://github.com/docker/buildx/releases/latest/download/buildx-linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
+                                chmod +x ~/.docker/cli-plugins/docker-buildx
+                            fi
+                            
                             echo "Setting up Docker Buildx..."
-                            docker buildx create mybuilder
-                            docker buildx inspect --bootstrap
+                            docker buildx create mybuilder || echo "Buildx builder already exists."
 
                             echo "Building Docker image with Buildx..."
                             docker buildx build --platform linux/amd64 -t \$DOCKER_IMAGE:\$COMMIT_ID --push .
